config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }

  get '/entities' => 'entities#display'

  post '/entities' => 'entities#create'

  get '/' => 'pages#dashboard'

  get '/entity/new' => 'entities#new', as: :new_entity
  get '/spanish' => redirect('/?lang=es')

  resources :patients
  get '/patients/:id' => 'patients#index'
  get 'patient/new' => 'patients#new'

  resources :medications
  get '/medications/new' => 'medications#new'
  get '/medications/show' => 'medications#show'
  get '/medications' => 'medications#index'

  get '/patient_medications/new' => 'patient_medications#new', as: :new_patient_medication

  post '/patient_medications' => 'patient_medications#create'

  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
    resources :patients, :medications
    root to: 'pages#dashboard'
  end

get '*path', to: redirect("/#{I18n.default_locale}/%{path}"), constraints: lambda { |req| !req.path.starts_with? "/#{I18n.default_locale}/" }
get '', to: redirect("/#{I18n.default_locale}/pages")

end

app/models/medication.rb
class Medication < ActiveRecord::Base
	has_many :patient_medications
end

app/controllers/medications_controller.rb
class MedicationsController < InheritedResources::Base

    def index
    @medications = Medication.all

    end

    def new
        @medication = Medication.new
    end

    def show

    end

    def update
     @medication = Medication.find(params[:id])
        @medication.update(medication_params)
        @medication.save
        redirect_to :back
    end

    def edit
    end

    def create
    end


    private

    def medication_params
      params.require(:medication).permit(:user_id, :name, :description)
    end
end

app/views/medications/_form.html.erb
<!-- This is a Medications Form Partial-->


<%= form_for @medication do |f| %>
    <div class = "medication_fields">
        <%= f.label :name, "Medication Name" %>
        <%= f.text_field :name, value: @medication.name %>

        <%= f.label :description, "Description:" %>
        <%= f.text_field :description, value: @medication.description %>
    </div>
<% end %>

app/views/medications/index.html.erb
<!-- Lists all medications. Can create new. -->
Add A Medication to Patient
<div class = "medication_list">
<% @medications = [] %>

	<% @medications.each do |med| %>
		<%= med.name %><br>
	<% end %>

	<%# medication.all %>
		<%# if medication.size == 0 %>
	<%# end %>

<% if @medications.empty? %>
	<em> No medications found. <%= link_to "Add a new medication for a patient here.", new_medication_path %>.</em>
<% end %>

</div>

app/views/medications/new.html.erb
Add A New Medication

<!-- Choose from a list of patients to associate a patient with a new medication -->
<%# collection_select @patients %>

<%= render 'form' %>

<%= link_to "Back", patients_path %>

app/views/medications/show.html.erb
<!-- This page might be unneccessary -->