config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }

  get '/entities' => 'entities#display'

  post '/entities' => 'entities#create'

  get '/' => 'pages#dashboard'

  get '/entity/new' => 'entities#new', as: :new_entity
  get '/spanish' => redirect('/?lang=es')

  resources :patients
  get '/patients/:id' => 'patients#index'
  get 'patient/new' => 'patients#new'

  resources :medications
  get '/medications/new' => 'medications#new'
  get '/medications/show' => 'medications#show'
  get '/medications' => 'medications#index'

  get '/patient_medications/new' => 'patient_medications#new', as: :new_patient_medication

  post '/patient_medications' => 'patient_medications#create'

  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
    resources :patients, :medications
    root to: 'pages#dashboard'
  end

get '*path', to: redirect("/#{I18n.default_locale}/%{path}"), constraints: lambda { |req| !req.path.starts_with? "/#{I18n.default_locale}/" }
get '', to: redirect("/#{I18n.default_locale}/pages")

end

app/views/pages/dashboard.html.erb
    <div class = "sidebar">
      <ul>

          <li><%=image_tag "plusicon.png", id: "sidebar-image"%> <%= link_to t(:managepatients), '/patients' %></li>
          <li><%= image_tag "adduser.png", id: "sidebar-image" %> <%= link_to t(:addapatient), new_patient_path %></li>
          <li><%= image_tag "medicine.png", id: "sidebar-image" %> <%= link_to t(:addmedication), new_patient_medication_path %></li>
          <!-- collection of patients in a scroll down bar -->
      </ul>
    </div>

    <!-- Sidebar Ends-->

<div class = "dash-container">

<h2>Calendar</h2><br>
<p2> Keep track of each patient profile's medication.</p2> <br>


 <div id="tabs_container">

      <!-- These are the tabs -->
      <ul class="tabs">
        <li class="active">
          <a href="#" rel="#tab_0_contents" class="tab">All</a>
        </li>
        <% @patients.each do |patient| %>
        <li>
          <a href="#" rel="#tab_<%= @patients.index(patient) +1%>_contents" class="tab">Patient <%= @patients.index(patient) + 1 %></a>
        </li>
        <% end %>
      </ul>

      <!-- This is used so the contents don't appear to the
           right of the tabs -->
      <div class="clear"></div>

      <!-- This is a div that holds all the tabbed contents -->
      <div class="tab_contents_container">

        <!-- Tab 1 Contents -->
        <div id="tab_0_contents" class="tab_contents tab_contents_active">
        <% @patient_medications.each do |dose| %>
            <li >
             <br><div class="all-patients-names">  <%= dose.dose_time.strftime("%I:%M %p") %>  <%= dose.patient.name %>  -  <%= dose.medication.name %> </div><br>

            </li>
        <% end %>
        </div>

        <!-- Tab 2 Contents -->
        <% @patients.each do |patient| %>
          <div id="tab_<%= @patients.index(patient)+1 %>_contents" class="tab_contents">
            <%= link_to patient.name, patient_path(patient) %><br>
            <ul>
             <br> <% patient.patient_medications.each do |patient_medication| %>
              <li>
                <%= patient_medication.dose_time.strftime("%I:%M %p") %>
                <%= patient_medication.medication.name %>
              </li>
              <% end %>
            </ul>
          </div>
        <% end %>

      </div>
    </div>
</div>